development:
  ASSET_KEY: "GOOGM74ZATVPEKMLAM4F"
  ASSET_SECRET: "zM9k6/bodUIkbMmCsWZLPbeDy4Xm2guMKsWSPAHJ"
  ASSET_BUCKET_NAME: "hungryhead-user-assets"
  PUBLIC_ASSET_BUCKET_NAME: "hungryhead-assets"
  PUSHER_APP_ID: "84302"
  PUSHER_APP_KEY: "a248114cc98a1f63cec5"
  PUSHER_APP_SECRET: "14b9398a1ec43310fde2"
  MANDRILL_USERNAME: 'gaurav@gauravtiwari.co.uk'
  MANDRILL_API_KEY: 'l2tn8zLPJC0L5L0QyN4pVA'
  FACEBOOK_APP_ID: '1535655483322723'
  FACEBOOK_APP_SECRET: 'a0fa47f96956e230f2a169b72d432ef4'
  TWITTER_APP_ID: '3bBqee7kGWtzxRE8Fq48LszyD'
  TWITTER_APP_SECRET: '5Qh3bf4eFR9OQT9paUfuuEQfmTu937XqEOWvOfvLSL3r9Hondv'
  LINKEDIN_APP_ID: '776r1nkp1mfg1t'
  LINKEDIN_APP_SECRET: '7Vh0gEZwr430E8c1'
  SKYLIGHT_AUTHENTICATION: 'QRVgnsGEMkzn6AQLRZzZ9I0xw8ZEfTujhXw5C7IUxxY'
  BUGSNAG_API_KEY: '26632c91b9d03184f8310ffb347415fb'