default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: localhost
  database: hungryhead_development

test:
  <<: *default
  host: localhost
  database: hungryhead_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
